# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=20, verbose_name='\u8d26\u53f7')),
                ('password', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('nickname', models.CharField(max_length=20, verbose_name='\u6635\u79f0')),
                ('sex', models.CharField(max_length=20, verbose_name='\u6027\u522b')),
                ('birthday', models.DateField(default='1970-1-1', verbose_name='\u751f\u65e5')),
                ('motto', models.CharField(max_length=20, verbose_name='\u7b7e\u540d')),
                ('head', models.FileField(upload_to='static/head', verbose_name='\u5934\u50cf')),
            ],
        ),
    ]
