# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='code',
            field=models.IntegerField(default=1, max_length=6, verbose_name='\u9a8c\u8bc1\u7801'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='code_end',
            field=models.TimeField(default='00:00:00', verbose_name='\u9a8c\u8bc1\u7801\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='information',
            name='code_start',
            field=models.TimeField(default='00:00:00', verbose_name='\u9a8c\u8bc1\u7801\u8d77\u59cb\u65f6\u95f4'),
        ),
    ]
