# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0002_auto_20170228_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(verbose_name='\u624b\u673a\u53f7')),
                ('code', models.IntegerField(verbose_name='\u9a8c\u8bc1\u7801')),
                ('code_start', models.TimeField(default='00:00:00', verbose_name='\u9a8c\u8bc1\u7801\u8d77\u59cb\u65f6\u95f4')),
                ('code_end', models.TimeField(default='00:00:00', verbose_name='\u9a8c\u8bc1\u7801\u7ed3\u675f\u65f6\u95f4')),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='code',
        ),
        migrations.RemoveField(
            model_name='information',
            name='code_end',
        ),
        migrations.RemoveField(
            model_name='information',
            name='code_start',
        ),
        migrations.AlterField(
            model_name='information',
            name='identification',
            field=models.IntegerField(verbose_name='\u8d26\u53f7'),
        ),
    ]
