# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0003_auto_20170228_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.CharField(max_length=6, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
    ]
