# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0004_auto_20170228_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(verbose_name='\u8d26\u53f7')),
                ('time_start', models.TimeField(default='00:00:00', verbose_name='\u8ba1\u65f6\u8d77\u59cb\u65f6\u95f4')),
                ('time_end', models.TimeField(default='00:00:00', verbose_name='\u8ba1\u65f6\u7ed3\u675f\u65f6\u95f4')),
                ('date', models.DateField(default='1970-1-1', verbose_name='\u65e5\u671f')),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='mark',
            field=models.IntegerField(default=0, max_length=20, verbose_name='\u79ef\u5206'),
        ),
        migrations.AlterField(
            model_name='information',
            name='motto',
            field=models.CharField(default='\u60a8\u5c1a\u672a\u8bbe\u7f6e\u7b7e\u540d', max_length=20, verbose_name='\u7b7e\u540d'),
        ),
        migrations.AlterField(
            model_name='information',
            name='nickname',
            field=models.CharField(default='\u60a8\u5c1a\u672a\u8bbe\u7f6e\u6635\u79f0', max_length=20, verbose_name='\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='information',
            name='sex',
            field=models.CharField(default='\u7537', max_length=20, verbose_name='\u6027\u522b'),
        ),
    ]
