# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0005_auto_20170303_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='mark',
            field=models.IntegerField(default=0, verbose_name='\u79ef\u5206'),
        ),
        migrations.AlterField(
            model_name='information',
            name='mark',
            field=models.IntegerField(default=0, verbose_name='\u79ef\u5206'),
        ),
    ]
