# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0006_auto_20170304_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='timing_hour',
            field=models.IntegerField(default=0, verbose_name='\u5c0f\u65f6\u6570'),
        ),
        migrations.AddField(
            model_name='information',
            name='timing_minute',
            field=models.IntegerField(default=0, verbose_name='\u5206\u949f\u6570'),
        ),
        migrations.AddField(
            model_name='information',
            name='timing_second',
            field=models.IntegerField(default=0, verbose_name='\u79d2\u6570'),
        ),
    ]
