# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0007_auto_20170310_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='timing_hour',
        ),
        migrations.RemoveField(
            model_name='information',
            name='timing_minute',
        ),
        migrations.RemoveField(
            model_name='information',
            name='timing_second',
        ),
        migrations.AddField(
            model_name='information',
            name='timing_useful',
            field=models.IntegerField(default=0, verbose_name='\u6709\u6548\u79d2\u6570'),
        ),
    ]
