# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0008_auto_20170310_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='timing_useful',
            field=models.IntegerField(default=0, verbose_name='\u6709\u6548\u79d2\u6570'),
        ),
    ]
