# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0009_timing_timing_useful'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='number',
            field=models.IntegerField(default=0, verbose_name='\u84dd\u7259\u8fde\u63a5\u4e2a\u6570'),
        ),
    ]
