# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-27 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0010_timing_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(verbose_name='\u8d26\u53f7')),
                ('goods_id', models.CharField(max_length=4, verbose_name='\u5546\u54c1ID')),
                ('shop_name', models.CharField(max_length=20, verbose_name='\u5e97\u94fa\u540d\u79f0')),
                ('goods_name', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('goods_image', models.FileField(upload_to='static/goods', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('mark_need', models.IntegerField(verbose_name='\u6240\u9700\u79ef\u5206')),
                ('money_need', models.IntegerField(verbose_name='\u6240\u9700\u91d1\u94b1')),
                ('status', models.IntegerField(default=1, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=4, verbose_name='\u5546\u54c1ID')),
                ('shop_name', models.CharField(max_length=20, verbose_name='\u5e97\u94fa\u540d\u79f0')),
                ('goods_name', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('goods_introduction', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u4ecb\u7ecd')),
                ('goods_image', models.FileField(upload_to='static/goods', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('mark_need', models.IntegerField(verbose_name='\u6240\u9700\u79ef\u5206')),
                ('money_need', models.IntegerField(verbose_name='\u6240\u9700\u91d1\u94b1')),
            ],
        ),
    ]
