# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0011_discount_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='money_need',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u6240\u9700\u91d1\u94b1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='money_need',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u6240\u9700\u91d1\u94b1'),
        ),
    ]
