# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-02 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0013_discount_goods_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='time_buy',
            field=models.DateTimeField(null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='discount',
            name='time_use',
            field=models.DateTimeField(null=True, verbose_name='\u4f7f\u7528\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='information',
            name='time_login',
            field=models.DateTimeField(null=True, verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='information',
            name='time_register',
            field=models.DateTimeField(null=True, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
    ]
