# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-02 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0014_auto_20170402_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code_end',
            field=models.TimeField(null=True, verbose_name='\u9a8c\u8bc1\u7801\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='code_start',
            field=models.TimeField(null=True, verbose_name='\u9a8c\u8bc1\u7801\u8d77\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='date',
            field=models.DateField(null=True, verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time_end',
            field=models.TimeField(null=True, verbose_name='\u8ba1\u65f6\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time_start',
            field=models.TimeField(null=True, verbose_name='\u8ba1\u65f6\u8d77\u59cb\u65f6\u95f4'),
        ),
    ]
