# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0015_auto_20170402_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=4, verbose_name='\u5546\u5bb6ID')),
                ('shop_name', models.CharField(max_length=20, verbose_name='\u5546\u5bb6\u540d\u79f0')),
                ('shop_address', models.CharField(max_length=100, verbose_name='\u5546\u5bb6\u5730\u5740')),
                ('shop_telephone', models.IntegerField(verbose_name='\u8054\u7cfb\u7535\u8bdd')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='goods_information',
            field=models.CharField(default=222, max_length=100, verbose_name='\u5546\u54c1\u4fe1\u606f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_information',
            field=models.CharField(default=222, max_length=100, verbose_name='\u5546\u54c1\u4fe1\u606f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_number',
            field=models.IntegerField(null=True, verbose_name='\u5546\u54c1\u5269\u4f59\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='goods',
            name='money_origin',
            field=models.DecimalField(decimal_places=2, default=222, max_digits=5, verbose_name='\u539f\u4ef7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='goods_introduction',
            field=models.CharField(max_length=100, verbose_name='\u4f7f\u7528\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='shop_name',
            field=models.CharField(max_length=20, verbose_name='\u5546\u5bb6\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_introduction',
            field=models.CharField(max_length=100, verbose_name='\u4f7f\u7528\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shop_name',
            field=models.CharField(max_length=20, verbose_name='\u5546\u5bb6\u540d\u79f0'),
        ),
    ]
