# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0018_discount_money_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='money_need',
            field=models.CharField(max_length=10, verbose_name='\u6240\u9700\u91d1\u94b1'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='money_origin',
            field=models.CharField(max_length=10, verbose_name='\u539f\u4ef7'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='money_need',
            field=models.CharField(max_length=10, verbose_name='\u6240\u9700\u91d1\u94b1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='money_origin',
            field=models.CharField(max_length=10, verbose_name='\u539f\u4ef7'),
        ),
    ]
