# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0019_auto_20170405_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_number',
            field=models.IntegerField(default=999, null=True, verbose_name='\u5546\u54c1\u5269\u4f59\u6570\u91cf'),
        ),
    ]
