# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0020_auto_20170405_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_telephone',
            field=models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
    ]
