# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0022_information_date_sign_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='mark_sign_in',
            field=models.IntegerField(default=0, verbose_name='\u79ef\u5206'),
        ),
    ]
