# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0023_information_mark_sign_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='day_sign_in',
            field=models.IntegerField(default=0, verbose_name='\u5df2\u8fde\u7eed\u7b7e\u5230\u5929\u6570'),
        ),
        migrations.AlterField(
            model_name='information',
            name='mark_sign_in',
            field=models.IntegerField(default=0, verbose_name='\u7b7e\u5230\u83b7\u5f97\u79ef\u5206'),
        ),
    ]
