# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0024_auto_20170414_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date_sign_in',
            field=models.DateField(default='1970-1-1', verbose_name='\u6700\u8fd1\u7b7e\u5230\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='information',
            name='time_register',
            field=models.DateTimeField(default='1970-1-1', verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
    ]
