# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0027_auto_20170415_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date_sign_in',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='\u6700\u8fd1\u7b7e\u5230\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='information',
            name='time_login',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='information',
            name='time_register',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
    ]
