# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0029_auto_20170506_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100, verbose_name='\u5e7f\u544a\u8bf4\u660e')),
                ('image', models.FileField(upload_to='static/advertisement', verbose_name='\u5e7f\u544a\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5e7f\u544a\u4fe1\u606f',
                'verbose_name_plural': '\u5e7f\u544a\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_sender', models.IntegerField(verbose_name='\u53d1\u9001\u8005\u8d26\u53f7')),
                ('identification_receiver', models.IntegerField(verbose_name='\u63a5\u6536\u8005\u8d26\u53f7')),
                ('time_request', models.DateTimeField(null=True, verbose_name='\u597d\u53cb\u7533\u8bf7\u53d1\u9001\u65f6\u95f4')),
                ('time_response', models.DateTimeField(null=True, verbose_name='\u597d\u53cb\u7533\u8bf7\u5904\u7406\u65f6\u95f4')),
                ('status', models.IntegerField(default=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u597d\u53cb\u4fe1\u606f',
                'verbose_name_plural': '\u597d\u53cb\u4fe1\u606f',
            },
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': '\u62b5\u7528\u5238\u4fe1\u606f', 'verbose_name_plural': '\u62b5\u7528\u5238\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '\u5546\u54c1\u4fe1\u606f', 'verbose_name_plural': '\u5546\u54c1\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': '\u624b\u673a\u9a8c\u8bc1\u7801', 'verbose_name_plural': '\u624b\u673a\u9a8c\u8bc1\u7801'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '\u5546\u5bb6\u4fe1\u606f', 'verbose_name_plural': '\u5546\u5bb6\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='timing',
            options={'verbose_name': '\u8ba1\u65f6\u4fe1\u606f', 'verbose_name_plural': '\u8ba1\u65f6\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.FileField(upload_to='static/shop', verbose_name='\u5546\u5bb6\u56fe\u7247'),
        ),
    ]
