# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-16 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0030_auto_20170506_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100, verbose_name='\u5956\u54c1\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u62bd\u5956\u4fe1\u606f',
                'verbose_name_plural': '\u62bd\u5956\u4fe1\u606f',
            },
        ),
    ]
