# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0031_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_prize',
            field=models.IntegerField(default=0, verbose_name='\u62bd\u5956\u6b21\u6570'),
        ),
    ]
