# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-17 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0032_user_num_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='words',
            field=models.CharField(max_length=20, verbose_name='\u5956\u54c1\u540d\u79f0'),
        ),
    ]
