# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0034_auto_20170810_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goodss',
        ),
    ]
