# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0035_remove_order_goodss'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goodss',
            field=models.ManyToManyField(to='miandui.Goods'),
        ),
    ]
