# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0037_auto_20170810_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_number',
            field=models.IntegerField(default=1, null=True, verbose_name='\u5546\u54c1\u6570\u91cf'),
        ),
    ]
