# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0038_auto_20170810_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=1, verbose_name='\u624b\u673a\u53f7'),
            preserve_default=False,
        ),
    ]
