# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miandui', '0040_auto_20170810_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='time_register',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
    ]
